package odyssey.app;

import java.util.List;

import odyssey.analyzers.AnalyzerBundle;
import soot.SootClass;

public class UMLGenerationApp {

  private Configuration config;
  private Processor processor;
  private AnalyzerBundle bundle;

  public UMLGenerationApp(Configuration config) {
    this.config = config;
    this.processor = Processor.getProcessor(this.config);
  }

  public void generate() {
    bundle = processor.executePipeline();
  }

  /**
   * Returns the list of Soot Classes generated by the generate() method
   * @return the classes processed
   */
  public List<SootClass> getClasses() {
    return bundle.classes;
  }

}
